# Generated by Django 3.1.6 on 2021-03-03 10:50

import apps.users.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210303_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='Mon commentaire', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=apps.users.models.MyUser, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
