# Generated by Django 3.1.6 on 2021-03-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210303_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='Mon commentaire', verbose_name=''),
        ),
    ]
