# Generated by Django 3.1.6 on 2021-04-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210415_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default=None, null = True, upload_to='blog/comments'),
        ),
    ]
