# Generated by Django 5.2.17 on 2026-09-16 13:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouygue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='album', verbose_name='photo')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "photo de l'album",
                'verbose_name_plural': "photos de l'album",
                'ordering': ['-date_posted'],
            },
        ),
    ]
