# Generated by Django 5.2.17 on 2026-09-16 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouygue', '0003_remove_discussions_and_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='folded_by',
            field=models.ManyToManyField(blank=True, related_name='announcements_folded', to=settings.AUTH_USER_MODEL),
        ),
    ]
