# Generated by Django 3.1.6 on 2021-03-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Utilisateur', max_length=100),
        ),
    ]
