# Generated by Django 5.2.17 on 2026-09-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='discussions_viewed',
        ),
    ]
