# Generated by Django 5.2.17 on 2026-09-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_myuser_discussions_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_comments',
            field=models.BooleanField(default=True, verbose_name="Me prévenir par e-mail quand quelqu'un commente mes publications"),
        ),
    ]
