# Generated by Django 3.1.6 on 2021-03-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210305_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='adresse email'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=40, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='prénom'),
        ),
    ]
