# Generated by Django 3.1.6 on 2021-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210305_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_default.jpg', upload_to='profile_pics'),
        ),
    ]
