# Generated by Django 3.1.6 on 2021-04-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210309_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='discussions_read',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='informations_read',
            field=models.SmallIntegerField(default=0),
        ),
    ]
