# Generated by Django 3.1.6 on 2021-04-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210408_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='discussions_read',
            new_name='activities_viewed',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='informations_read',
            new_name='discussions_viewed',
        ),
        migrations.AddField(
            model_name='myuser',
            name='informations_viewed',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='reservations_viewed',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='works_viewed',
            field=models.SmallIntegerField(default=0),
        ),
    ]
