# Generated by Django 3.1.6 on 2021-04-23 08:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210414_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='profile_default.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[1024, 768], upload_to='profile_pics'),
        ),
    ]
