# Generated by Django 5.2.17 on 2026-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopost',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Reste en tête des infos pratiques : ouverture de la maison, contacts utiles…', verbose_name='Fiche épinglée'),
        ),
    ]
