# Generated by Django 3.1.6 on 2021-04-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_infocomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infocomment',
            old_name='post',
            new_name='infopost',
        ),
    ]
