# Generated by Django 3.1.6 on 2021-04-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20210412_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocomment',
            name='content',
            field=models.TextField(verbose_name=''),
        ),
    ]
