# Generated by Django 3.1.6 on 2021-04-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20210415_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocomment',
            name='image',
            field=models.ImageField(null=True, upload_to='info/comments'),
        ),
    ]
