# Generated by Django 3.1.6 on 2021-03-09 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='activities')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('difficulty', models.SmallIntegerField(choices=[(0, 'Très facile'), (1, 'Facile'), (2, 'Moyen'), (3, 'Difficile'), (4, 'Très difficile')], default=0)),
                ('image', models.ImageField(default='activity_default.jpg', upload_to='activities')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-date_posted'],
            },
        ),
    ]
