# Generated by Django 3.1.6 on 2021-04-23 15:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Description')),
                ('content2', models.TextField(verbose_name='Précisions')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('difficulty', models.SmallIntegerField(choices=[(0, 'Très facile'), (1, 'Facile'), (2, 'Moyen'), (3, 'Difficile'), (4, 'Très difficile')], default=0, verbose_name='Difficulté')),
                ('duration', models.CharField(max_length=20, verbose_name='Durée')),
                ('distance', models.CharField(max_length=20, verbose_name='Temps de route')),
                ('image', models.ImageField(default='activity_default.jpg', upload_to='activities')),
                ('image2', models.ImageField(default='activity_default.jpg', upload_to='activities')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(null=True, upload_to='activities/comments')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
