# Generated by Django 5.2.17 on 2026-09-16 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Description')),
                ('content2', models.TextField(blank=True, verbose_name='Précisions')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('difficulty', models.SmallIntegerField(choices=[(0, 'Très facile'), (1, 'Facile'), (2, 'Moyen'), (3, 'Difficile'), (4, 'Très difficile')], default=0, verbose_name='Difficulté')),
                ('duration', models.CharField(max_length=20, verbose_name='Durée')),
                ('distance', models.CharField(max_length=20, verbose_name='Temps de route')),
                ('image', models.ImageField(blank=True, upload_to='activities')),
                ('image2', models.ImageField(blank=True, upload_to='activities')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, upload_to='comments')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
