# Generated by Django 3.1.6 on 2021-03-09 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
