# Generated by Django 3.1.6 on 2021-03-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='distance',
            field=models.SmallIntegerField(default=0),
        ),
    ]
