# Generated by Django 3.1.6 on 2021-04-11 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='difficulty',
            field=models.SmallIntegerField(choices=[(0, 'Très facile'), (1, 'Facile'), (2, 'Moyen'), (3, 'Difficile'), (4, 'Très difficile')], default=0, verbose_name='Difficulté'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Durée'),
        ),
    ]
