# Generated by Django 3.1.6 on 2021-04-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20210411_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
