# Generated by Django 3.1.6 on 2021-04-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activitycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='content_2',
            field=models.TextField(default='content 2', verbose_name='Précisions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.CharField(max_length=20, verbose_name='Temps de route'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.CharField(max_length=20, verbose_name='Durée'),
        ),
    ]
