# Generated by Django 3.1.6 on 2021-04-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20210414_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='content_2',
            new_name='content2',
        ),
        migrations.AddField(
            model_name='activity',
            name='image2',
            field=models.ImageField(default='activity_default.jpg', upload_to='activities'),
        ),
    ]
