# Generated by Django 3.1.6 on 2021-04-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_auto_20210414_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycomment',
            name='content',
            field=models.TextField(verbose_name=''),
        ),
    ]
