# Generated by Django 3.1.6 on 2021-04-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_auto_20210423_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(default='activity_default.jpg', upload_to='activities'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image2',
            field=models.ImageField(default='activity_default.jpg', upload_to='activities'),
        ),
    ]
