# Generated by Django 3.1.6 on 2021-04-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_auto_20210423_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityImage',
        ),
    ]
