# Generated by Django 3.1.6 on 2021-04-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_delete_activityimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(default='activity_default.jpg', null=True, upload_to='activities'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image2',
            field=models.ImageField(default='activity_default.jpg', null=True, upload_to='activities'),
        ),
    ]
