# Generated by Django 3.1.6 on 2021-04-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.TextField(default='Description'),
        ),
    ]
