# Generated by Django 5.2.17 on 2026-09-16 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('declined', 'Refusé'), ('cancelled', 'Annulé'), ('outdated', "Plus d'actualité")], default='pending', max_length=10)),
                ('offered_start', models.DateField()),
                ('offered_end', models.DateField()),
                ('requested_start', models.DateField()),
                ('requested_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='agenda.reservation')),
                ('requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='agenda.reservation')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'échange de séjour',
                'verbose_name_plural': 'échanges de séjours',
                'ordering': ['-created_at'],
            },
        ),
    ]
