# Generated by Django 5.2.17 on 2026-09-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='anchor_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de référence'),
        ),
    ]
