# Generated by Django 3.1.6 on 2021-04-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20210418_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.TextField(blank=True, default='Description'),
        ),
    ]
