# Generated by Django 5.2.17 on 2026-09-16 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.SmallIntegerField(default=0, verbose_name='Nouveau Total')),
                ('description', models.CharField(max_length=64, verbose_name='Brève Description')),
            ],
            options={
                'verbose_name_plural': 'Budget',
            },
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('progress', models.SmallIntegerField(default=0, verbose_name='Progression')),
                ('goal', models.SmallIntegerField(default=0, verbose_name='Objectif')),
            ],
            options={
                'verbose_name_plural': 'Funding',
            },
        ),
    ]
