# Generated by Django 5.2.17 on 2026-09-16 10:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Description')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.SmallIntegerField(default=0, verbose_name='Coût estimé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='work')),
                ('categories', models.SmallIntegerField(choices=[(0, 'Bricolage'), (1, 'Jardinage'), (2, 'Plomberie'), (3, 'Maçonnerie'), (4, 'Autre')], default=0, verbose_name='Catégories')),
                ('state', models.SmallIntegerField(choices=[(0, 'À faire'), (1, 'En cours'), (2, 'Terminé')], default=0, verbose_name='État')),
                ('status', models.SmallIntegerField(choices=[(0, 'Peut attendre'), (1, 'Important'), (2, 'Urgent')], default=1, verbose_name='Statut')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, upload_to='comments')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.work')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
