# Generated by Django 3.1.6 on 2021-04-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20210411_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='categories',
            field=models.SmallIntegerField(choices=[(0, 'Bricolage'), (1, 'Jardinage'), (2, 'Plomberie'), (3, 'Maçonnerie'), (4, 'Autre')], default=0, verbose_name='Catégories'),
        ),
    ]
