# Generated by Django 3.1.6 on 2021-04-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_workcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcomment',
            name='content',
            field=models.TextField(verbose_name=''),
        ),
    ]
